version: "3.9"

services:
  web:
    build: .
    container_name: urlshortener_app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=change-me
      - DJANGO_SETTINGS_MODULE=url_shortener.settings
    volumes:
      - .:/app
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
